- packages/friends/yml/en/joseph-edgerton.yml
Hey, I made a yaml so I could kite all night.
> created yaml for joseph edgerton

- packages/jones/src/adoc-iro-grammar.txt
- packages/jones/src/components/StyledEditor.js
- packages/jones/src/components/adoc-mode.js
> jones: improve syntax highlighting

- packages/hilkiah/src/__tests__/find-tests.js
- packages/hilkiah/src/disambiguate.js
> hilkiah: fix bad romans find

- packages/kite/src/publish/sass/common.scss
> kite: justify postscript

- packages/jones/src/components/Editor.js
- packages/jones/src/components/adoc-mode.js
- packages/jones/src/components/adoc-snippets.js
- packages/jones/src/lib/__tests__/format-tests.js
- packages/jones/src/lib/format.js
- packages/styleguide/src/components/Snippet.js
- packages/styleguide/src/sections/Emphasis.js
- packages/styleguide/src/sections/Gotchas.js
- packages/styleguide/src/sections/Quotes.js
- packages/styleguide/src/sections/Styling.js
- packages/styleguide/src/sections/SubHeadings.js
> Jones snippets

- packages/bot/src/check/lint.js
> bot: paginate lint annotations

- packages/jones/src/components/Search/index.js
> jones: slightly improve usability of search

- packages/asciidoc/src/lint/line-rules/unintentional-list-item.ts
- packages/fell/fell.js
- packages/jones/src/actions/github-actions.tsx
- packages/jones/src/actions/index.tsx
- packages/jones/src/components/Editor.tsx
- packages/jones/src/components/StyledEditor.tsx
- packages/jones/src/components/Task.tsx
- packages/jones/src/components/TaskList.tsx
- packages/jones/src/components/Work.tsx
- packages/jones/src/components/adoc-mode.ts
- packages/jones/src/lib/github-api.ts
- packages/jones/src/migrations/__tests__/pr-number.spec.ts
- packages/jones/src/migrations/index.ts
- packages/jones/src/migrations/pr-number-to-pull-request-object.ts
- packages/jones/src/reducers/__tests__/tasks-reducer-tests.ts
- packages/jones/src/reducers/tasks-reducer.ts
- packages/jones/src/store.tsx
- packages/jones/src/type.ts
- packages/jones/tsconfig.json
- packages/styleguide/src/sections/Letters.js
- tsconfig.json
>  jones: lock merged/closed tasks

- packages/asciidoc/src/job/source-spec.ts
- packages/jones/src/App.tsx
- packages/jones/src/components/Editor.tsx
- packages/jones/src/components/Preview/index.tsx
- packages/jones/src/components/editor-key-commands.ts
- packages/jones/src/index.css
- packages/jones/src/lib/search.ts
- packages/kite/src/publish/cli/index.js
- packages/styleguide/src/components/Content.js
- packages/styleguide/src/components/Sidebar.js
- packages/styleguide/src/sections/Letters.js
- packages/styleguide/src/sections/Videos.js
- packages/styleguide/src/sections/index.js
- packages/types/types.ts
> Misc aftermath

- packages/asciidoc/src/job/__tests__/prepare-adoc.spec.ts
- packages/asciidoc/src/job/__tests__/source-spec.spec.ts
- packages/asciidoc/src/job/prepare-adoc.ts
- packages/cover/src/components/App.tsx
- packages/cover/src/components/Cover/Diamonds.tsx
- packages/cover/src/components/Cover/types.ts
- packages/cover/src/scripts/friend-data.ts
> more work on covers

- packages/friends/yml/en/john-barclay.yml
- packages/friends/yml/en/john-burnyeat.yml
- packages/friends/yml/en/john-churchman.yml
- packages/friends/yml/en/john-conran.yml
- packages/friends/yml/en/john-fothergill.yml
- packages/friends/yml/en/john-gratton.yml
- packages/friends/yml/en/john-griffith.yml
- packages/friends/yml/en/john-richardson.yml
- packages/friends/yml/en/john-roberts.yml
- packages/friends/yml/en/john-spalding.yml
- packages/friends/yml/en/john-wigham.yml
- packages/friends/yml/en/john-woolman.yml
- packages/friends/yml/en/joseph-edgerton.yml
- packages/friends/yml/en/joseph-phipps.yml
- packages/friends/yml/en/joseph-pike.yml
- packages/friends/yml/en/martha-routh.yml
- packages/friends/yml/en/mary-dudley.yml
- packages/friends/yml/en/mary-peisley-neale.yml
- packages/friends/yml/en/rebecca-hubbs.yml
- packages/friends/yml/en/rebecca-jones.yml
- packages/friends/yml/en/richard-jordan.yml
Hey... Here is another chunk of blurb work. I probably have one more chunk left to finish them all. Be ruthless if you don't like something, or have better ideas, etc. It's kinda hard to think of something different to say about each one.
> blurb work part 2

- .eslintrc.js
- packages/ui/.storybook/config.js
- packages/ui/package.json
- packages/ui/src/Button.tsx
- packages/ui/src/UnstyledButton.tsx
- packages/ui/src/cart/Item.tsx
- packages/ui/src/cart/ItemQuantity.tsx
- packages/ui/src/cart/index.tsx
- packages/ui/src/checkout/CheckoutMachine.ts
- packages/ui/src/checkout/CollectAddress.tsx
- packages/ui/src/checkout/CollectCreditCard.tsx
- packages/ui/src/checkout/CollectEmail.tsx
- packages/ui/src/checkout/ConfirmShipping.tsx
- packages/ui/src/checkout/CostExplanation.tsx
- packages/ui/src/checkout/Flow.tsx
- packages/ui/src/checkout/Input.ts
- packages/ui/src/checkout/MessageThrobber.tsx
- packages/ui/src/checkout/Modal.tsx
- packages/ui/src/checkout/Success.tsx
- packages/ui/src/checkout/types.ts
- packages/ui/src/theme.ts
- packages/ui/stories/cart.stories.tsx
- packages/ui/stories/checkout-flow.stories.tsx
- packages/ui/stories/checkout.stories.tsx
- packages/ui/stories/index.stories.tsx
- yarn.lock
> super-rough checkout components and workflow

- packages/friends/yml/en/robert-barclay.yml
- packages/friends/yml/en/samuel-crisp.yml
- packages/friends/yml/en/samuel-neale.yml
- packages/friends/yml/en/samuel-rundell.yml
- packages/friends/yml/en/sarah-grubb.yml
- packages/friends/yml/en/stephen-crisp.yml
- packages/friends/yml/en/thomas-kite.yml
- packages/friends/yml/en/thomas-scattergood.yml
- packages/friends/yml/en/thomas-shillitoe.yml
- packages/friends/yml/en/thomas-story.yml
- packages/friends/yml/en/thomas-wilson.yml
- packages/friends/yml/en/william-caton.yml
- packages/friends/yml/en/william-dewsbury.yml
- packages/friends/yml/en/william-edmundson.yml
- packages/friends/yml/en/william-evans.yml
- packages/friends/yml/en/william-penn.yml
- packages/friends/yml/en/william-savery.yml
- packages/friends/yml/en/william-sewel.yml
- packages/friends/yml/en/william-shewen.yml
Here's the last third of the blurb work. I think that all of these could be improved, but (after you review them) they're probably decent for now.
> the last of the blurb work

- packages/evans/src/lib/__tests__/url.spec.ts
- packages/friends/yml/en/george-fox.yml
- packages/friends/yml/en/george-whitehead.yml
- packages/friends/yml/en/hugh-turford.yml
- packages/friends/yml/en/james-nayler.yml
- packages/friends/yml/en/john-banks.yml
- packages/friends/yml/en/john-burnyeat.yml
Hope I didn't mess anything up!
> added some audio info

- packages/friends/yml/es/francis-howgill.yml
fixed the shorter title, and added the Friend and book descriptions
> spanish howgill title and descriptions

- packages/friends/yml/en/christopher-story.yml
- packages/friends/yml/en/mary-alexander.yml
- packages/friends/yml/en/oliver-sansom.yml
- packages/friends/yml/en/samuel-bownas.yml
I don't love any of these. It seems to be getting harder to write something different or interesting about all of these people who are all amazing for the same reason. Feel free to change, tweak, or destroy.
> four new blurbs

- packages/friends/yml/en/mary-peisley-neale.yml
- packages/friends/yml/en/oliver-sansom.yml
- packages/friends/yml/en/rebecca-hubbs.yml
- packages/friends/yml/en/rebecca-jones.yml
- packages/friends/yml/en/richard-davies.yml
- packages/friends/yml/en/richard-jordan.yml
- packages/friends/yml/en/robert-barclay.yml
- packages/friends/yml/en/samuel-bownas.yml
- packages/friends/yml/en/samuel-crisp.yml
- packages/friends/yml/en/samuel-fothergill.yml
- packages/friends/yml/en/samuel-neale.yml
- packages/friends/yml/en/samuel-rundell.yml
- packages/friends/yml/en/sarah-grubb.yml
- packages/friends/yml/en/sarah-stephenson.yml
- packages/friends/yml/en/stephen-crisp.yml
- packages/friends/yml/en/thomas-ellwood.yml
- packages/friends/yml/en/thomas-kite.yml
- packages/friends/yml/en/thomas-scattergood.yml
- packages/friends/yml/en/thomas-shillitoe.yml
- packages/friends/yml/en/thomas-story.yml
Hey... after putting in some of these quotes about Friends, I started to wonder if maybe a few of them leaned too much towards "exalting the creature". I can't really tell if its a real scruple, or just a fear of a scruple, so I'd be interested in hearing what you think/feel... especially about the quotes that make certain friends seem super amazing (which they were).
> yaml work part 5

- packages/evans/package.json
- packages/evans/src/pages/index.tsx
- packages/types/src/types.ts
- packages/ui/package.json
- packages/ui/src/pages/home/FormatsBlock.css
- packages/ui/src/pages/home/FormatsBlock.tsx
- packages/ui/src/pages/home/SubHeroBlock.css
- packages/ui/src/pages/home/SubHeroBlock.tsx
- yarn.lock
Together with 4256b8cf8adac7a87abc8eae63cdd913e5afff11, and dc027b4450d9dda0d2cda97b451c3727f7121c08 -- closes #445 and closes #446.
> optimize homepage non-bg images

- packages/adoc-convert/src/__tests__/prepare-adoc.spec.ts
- packages/adoc-convert/src/__tests__/process-document.spec.ts
- packages/adoc-convert/src/prepare-adoc.ts
- packages/adoc-lint/src/__tests__/fix-single-pass.spec.ts
- packages/adoc-lint/src/fix-single-pass.ts
- packages/adoc-lint/src/line-rules/__tests__/footnote-split-spacing.spec.ts
- packages/adoc-lint/src/line-rules/footnote-split-spacing.ts
- packages/adoc-lint/src/line-rules/index.ts
- packages/cli/src/cmd/convert/__tests__/footnote.xml
- packages/cli/src/cmd/convert/__tests__/handler.spec.ts
- packages/cli/src/cmd/convert/handler.ts
- packages/cli/src/lint/display.ts
- packages/friends/yml/__tests__/file.spec.ts
- packages/jones/src/actions/github-actions.ts
- packages/jones/src/lib/github-api.ts
> asciidoc conversion/lint improvements

- packages/ui/src/cart/index.tsx
- packages/ui/src/checkout/Delivery.tsx
- packages/ui/src/checkout/Input.css
- packages/ui/src/checkout/Input.tsx
This reverts commit eb303aea9c6d29e74078700c489262e52b22330c.
> Revert "ui: restrict shipping to US during COVID-19 intl. shipping ban"

- packages/adoc-convert/src/__tests__/headings.spec.ts
- packages/adoc-convert/src/headings.ts
- packages/cli/src/cmd/make-ref/intermediate-titles.adoc
- packages/cli/src/cmd/publish/handler.ts
- packages/doc-css/src/css/common.css
- packages/doc-css/src/css/ebook/intermediate-title.css
- packages/doc-css/src/css/ebook/kf8.css
- packages/doc-css/src/css/pdf/intermediate-title.css
- packages/doc-css/src/css/pdf/paperback-interior.css
- packages/doc-css/src/css/pdf/toc.css
- packages/doc-css/src/css/pdf/web-pdf.css
- packages/doc-css/src/ebook.ts
- packages/doc-css/src/paperback-interior.ts
- packages/doc-css/src/web-pdf.ts
- packages/doc-manifests/src/ebook/frontmatter.ts
- packages/doc-manifests/src/ebook/nav.ts
- packages/doc-manifests/src/paperback-interior/frontmatter.ts
- packages/evans/src/build/source-nodes.ts
- packages/styleguide/src/adoc/intermediate-title.adoc
- packages/styleguide/src/sections/Styling.tsx
- packages/types/src/types.ts
> support intermediate titles in docs

- packages/adoc-convert/src/__tests__/prepare-adoc.spec.ts
- packages/adoc-convert/src/prepare-adoc.ts
- packages/adoc-lint/src/__tests__/fix-single-pass.spec.ts
- packages/adoc-lint/src/block-rules/__tests__/numbered-group.spec.ts
- packages/adoc-lint/src/block-rules/__tests__/wrapping-blocks.spec.ts
- packages/adoc-lint/src/block-rules/index.ts
- packages/adoc-lint/src/block-rules/numbered-group.ts
- packages/adoc-lint/src/block-rules/wrapping-block.ts
- packages/adoc-lint/src/fix-single-pass.ts
- packages/adoc-lint/src/line-rules/__tests__/postscript-header.spec.ts
- packages/adoc-lint/src/line-rules/__tests__/unwrapped-postscript.spec.ts
- packages/adoc-lint/src/line-rules/index.ts
- packages/adoc-lint/src/line-rules/postscript-header.ts
- packages/adoc-lint/src/line-rules/unwrapped-postscript.ts
- packages/cli/src/cmd/make-ref/postscripts.adoc
- packages/doc-css/src/css/common.css
- packages/doc-css/src/css/pdf/web-pdf.css
- packages/styleguide/src/adoc/postscript.adoc
- packages/styleguide/src/sections/Letters.tsx
> Overhaul postscripts

- packages/functions/src/site/print-job-create.ts
> functions: temp - skip failure to re-verify payment intent during print job create

- .github/workflows/ci-cd.yml
- packages/adoc-convert/src/__tests__/utils.spec.ts
- packages/adoc-convert/src/index.ts
- packages/adoc-convert/src/utils.ts
- packages/doc-css/src/css/pdf/toc.css
- packages/doc-html/src/nav.ts
- packages/doc-manifests/package.json
- packages/doc-manifests/src/frontmatter.ts
- packages/doc-manifests/src/paperback-interior/__tests__/frontmatter.spec.ts
- packages/doc-manifests/src/paperback-interior/frontmatter.ts
- packages/evans/package.json
- packages/evans/src/build/algolia.ts
- packages/evans/src/build/helpers.ts
- packages/evans/src/build/news-feed.ts
- packages/evans/src/build/source-nodes.ts
> multi-col paperback table-of-contents for certain docs

- packages/cli/src/cmd/audio/SoundCloudClient.ts
- packages/cli/src/cmd/audio/handler.ts
- packages/cli/src/cmd/audio/index.ts
- packages/evans/_redirects
- packages/friends/yml/en/charles-marshall.yml
- packages/friends/yml/en/elizabeth-stirredge.yml
- packages/friends/yml/en/elizabeth-webb.yml
- packages/friends/yml/en/john-burnyeat.yml
- packages/friends/yml/en/john-crook.yml
- packages/friends/yml/en/john-griffith.yml
- packages/friends/yml/en/john-richardson.yml
- packages/friends/yml/en/joseph-pike.yml
- packages/friends/yml/en/stephen-crisp.yml
- packages/friends/yml/en/thomas-story.yml
- packages/functions/src/site/__tests__/site-fns.integration.ts
- packages/ui/src/checkout/services/__tests__/CheckoutService.integration.ts
> new titip v1 standalone audio files (without TITIP chapter prelude)
